### ISSUE TITLE
feature request: add ability to make RPC calls to Parity nodes in addition to infura

### ISSUE THREAD

**Issue by mingfang** [Great-Hill-Corporation/quickBlocks#538] opened 2017-12-26 04:42 UTC
Currently "remote" is hard coded to call infura. I would like to be able to set "remote:http://myhost:8545" to make RPC calls to arbitrary nodes.

**Comment by tjayrush** [comment] 2017-12-26 16:26
This is already possible. In fact, this is how it works if you use it out of the box. The code you're looking for is here: https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/libs/etherlib/node.cpp#L40.

The way it's supposed to work is, if you use `etherlib_init("binary")` when you initialize the library, it will read the data from the local node and cache it in a binary file so that the next time you ask for that same block it will be much faster. (This is also true of etherlib_init("infura") by the way.)

Do me a favor so I can help you better. Post the relevant portions of your code here and I can help you out. This needs to be better documented.

**Comment by mingfang** [comment] 2017-12-26 16:33
@tjayrush How can I read from a remote node instead of the local node.
In https://github.com/Great-Hill-Corporation/quickBlocks/blob/e8340525edb6aa2a83988aee2443ca7d48c7669c/src/libs/etherlib/node.cpp#L41 I need to be able to set CURLOPT_URL to "http://mynode:8545" instead of "http://localhost:8545"

**Comment by tjayrush** [comment] 2017-12-26 17:02
The easiest way is to simply change that string and re-compile. (Simply change the string.)

Are you a programmer? I don't have time right now to make this configurable myself, but I can give you some very simple instructions on how you can make this a configurable option and you can then make a pull request which I'd be happy to merge in.

If not, I can write a bug and add the feature as soon as I can get to it. Let me know what you would like me to do.

**Comment by mingfang** [comment] 2017-12-26 17:07
I haven't written cpp in years now, but if you can give me some pointers making it configurable I can try to do it. I will also need option to add additional curl headers for things like api keys. Thanks.

Also, I don't think etherlib_init("binary") would create the local cache automatically. When running getBlook, I had to pass in the --force option to create the local cache.

**Comment by tjayrush** [comment] 2017-12-26 21:37
You're right about the --force option for the getBlock tool. We have other code (that is not currently open source) that behaves as I described. Sorry for the confusion.

As you probably can tell, quickBlocks is currently `alpha` software. (A work in progress.) Help me to understand exactly what you're looking to do and I will program it for you. I'll make it a priority.

Are you hoping to simply use the command line tools (such as getBlock) to pull data faster and send it on to another process? Are you writing code C++ that uses the quickBlocks libraries?

The reason I'm asking is that I am actually working on code that will make customizing the behavior of Curl easier to specify, and I can incorparate functionality that you need in that work. Please feel free to send me an email (jrush@quickblocks.io) if you think it would ease the process. I'm happy to help.

**Comment by tjayrush** [comment] 2018-01-10 17:59
The latest 'develop' build has some new features that will allow you to specify the CURL headers and baseURL. Here's a simple example:

```
int main(void) {
    etherlib_init();
    getCurlContext()->headers  = "Content-Type: application/json\n";
    getCurlContext()->baseURL = "http://localhost:8545";
    CBlock block;
    getBlock(block, 4001001);
    etherlib_cleanup();
}
```

This should pull the block from whatever node you specify and send whatever headers you specify. The headers get parsed [here](https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/libs/etherlib/node_curl.cpp#L103). As you can see, you need to separate the headers from each other with '\n'.

Please do me a favor--if you try this--please let me know if it works. It works on my system, but I'd like to hear your experience.

**Comment by tjayrush** [comment] 2018-02-01 02:57
I'm going to close this, assuming it's working as designed.

**Closed by tjayrush** 2018-02-01 02:57 UTC
Labels: build-docs, libs-etherlib, status-inprocess

**Comment by tjayrush** [comment] 2019-01-07 23:19
This is true, but inadequate. I am closing this, but the issue is still open at #969
