### ISSUE TITLE
Bug present at most of the tools and apps

### ISSUE THREAD

**Issue by crodnun** [Great-Hill-Corporation/quickBlocks#210] opened 2017-08-10 15:11 UTC
When you run any tool, this way, example for ethName but applies to any tool and app I think:

./ethName -       (with only a dash)

it gest stalled till you kill it with a Ctrl+C

The same happens at most of the tools and apps tested so far, just to check that it is a general behaviour probably at libs shared by all them.

**Comment by tjayrush** [comment] 2017-08-10 15:38
It is general. I think it was originally intended to allow for piping the results of one tool into another just like the Linux command 'grep' for example which required a filename unless '-' is used in which case it gets its input from a pipe. 'grep' also just hangs waiting for input and doesn't quit until you hit control+C or control+D.

> echo "Jay" | grep Jay -
Jay

**Comment by tjayrush** [comment] 2017-08-12 02:26
I'm not sure if I should simply close these or re-assign them to you and let you close them. Please advise.

**Comment by crodnun** [comment] 2017-08-14 09:07
OK,
Tested, it is intended to pipe with files:

If we create a file with this content (input.txt), add these three lines:

-c rob
-c ghc
-c 17

And run the command with a pipe, passing the input file:

cat input.txt | ./ethName -

It executes all the commands at the same time:

5 matches
0 matches
209 matches

**Comment by tjayrush** [comment] 2017-08-14 12:03
I think this is how I intended it to work. If you agree, please go ahead and close this.

**Comment by tjayrush** [comment] 2018-11-23 15:33
Works as intended

**Closed by tjayrush** 2018-11-23 15:33 UTC
Labels: Bug, TL-utillib, TT-all_tools
